#!/usr/bin/env python3
"""Generate poll-secret.js — the CCGate-encrypted Supabase poll secret.

You run this. It asks for the SAME passphrase that unlocks /poll-admin/ and
/class-console/. It then invents a random machine secret, encrypts it under
that passphrase in exactly the format auth.js expects, and prints the one SQL
line you paste into Supabase.

Nobody -- not Claude, not the repo, not a student -- ever sees either value.
The passphrase is never stored, and the machine secret is never printed except
in the SQL line you paste and then discard.

    python3 make-poll-secret.py
"""
import base64, getpass, hashlib, json, os, secrets, sys
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

ITER = 600_000          # must match the other CCGate payloads on this site
B = lambda x: base64.b64encode(x).decode()

def check(passphrase):
    """Decrypt the existing class-console payload. Wrong passphrase -> stop."""
    import re
    here = os.path.dirname(os.path.abspath(__file__))
    ref = os.path.join(here, "class-console", "index.html")
    if not os.path.exists(ref):
        print("! class-console/index.html not found -- cannot verify the passphrase.")
        return
    m = re.search(r'payload:\s*(\{.*?\})\s*,\s*\n', open(ref, encoding="utf-8").read(), re.S)
    if not m:
        print("! could not find the class-console payload -- skipping verification.")
        return
    pl = json.loads(m.group(1))
    key = hashlib.pbkdf2_hmac("sha256", passphrase.encode(),
                              base64.b64decode(pl["salt"]), pl["iter"], dklen=32)
    try:
        AESGCM(key).decrypt(base64.b64decode(pl["iv"]), base64.b64decode(pl["ct"]), None)
    except Exception:
        sys.exit("\nThat is NOT the passphrase that unlocks /class-console/ and /poll-admin/.\n"
                 "It has to be the same one, or your browser can never decrypt what this\n"
                 "script writes -- and the failure would be silent.\n"
                 "Nothing was written. Try again with the shared instructor passphrase.")
    print("Passphrase verified against the existing class-console payload.\n")


def main():
    print(__doc__.split("\n\n")[1].replace("\n", " "), "\n")
    p1 = getpass.getpass("CCGate passphrase (same as poll-admin): ").strip()
    if not p1:
        sys.exit("No passphrase given.")
    p2 = getpass.getpass("Again, to be sure: ").strip()
    if p1 != p2:
        sys.exit("They do not match. Nothing was written.")

    # Prove it is the RIGHT passphrase before writing anything.
    # It must be the one that already unlocks class-console, or the browser
    # will never be able to decrypt what we are about to write -- and the
    # failure would be silent and, on a projector, invisible.
    check(p1)

    # The Supabase-side secret. Random, machine-only, never typed by a human.
    poll_secret = secrets.token_urlsafe(32)

    salt, iv = os.urandom(16), os.urandom(12)
    key = hashlib.pbkdf2_hmac("sha256", p1.encode(), salt, ITER, dklen=32)
    ct = AESGCM(key).encrypt(iv, json.dumps({"poll_secret": poll_secret}).encode(), None)
    payload = {"salt": B(salt), "iv": B(iv), "ct": B(ct), "iter": ITER}

    out = ("/* Generated by make-poll-secret.py -- do not hand-edit.\n"
           " * The Supabase poll secret, encrypted under the shared instructor\n"
           " * passphrase (PBKDF2-SHA256 %d -> AES-GCM), same scheme as the\n"
           " * class-console and poll-admin payloads. Safe to publish.\n"
           " */\n"
           "window.POLL_SECRET_PAYLOAD = %s;\n") % (ITER, json.dumps(payload))

    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "poll-secret.js")
    with open(path, "w") as f:
        f.write(out)

    print("\nWrote", path)
    print("\n" + "=" * 72)
    print("PASTE THIS ONE LINE INTO THE SUPABASE SQL EDITOR, THEN PRESS RUN:")
    print("=" * 72)
    print("insert into public.poll_secrets (k, v)")
    print("values ('instructor', '%s')" % poll_secret)
    print("on conflict (k) do update set v = excluded.v;")
    print("=" * 72)
    print("\nThen: git add poll-secret.js && git commit && git push")
    print("Do not paste the line above into a chat -- it is the live secret.\n")

if __name__ == "__main__":
    main()
