/* Generated by rotate.py -- do not hand-edit.
 * Supabase poll secret, encrypted under the shared instructor passphrase
 * (PBKDF2-SHA256 600000 -> AES-GCM). Ciphertext only; safe to publish.
 */
window.POLL_SECRET_PAYLOAD = {"salt": "qma6ctwA0lt5l/IUzUlg0g==", "iv": "UNpCb53ehUohxSwM", "ct": "r7s26e1PdOw+eS1BcktaAPGfkRkHicppANgZ+WCA/8AKEGGPicE5VmuhnDF2HW1uAe3bQjzsk30puOaQMUS1SjtLU4FQSv9KWFzzWA8x", "iter": 600000};
