/* Generated by make-poll-secret.py -- do not hand-edit.
 * The Supabase poll secret, encrypted under the shared instructor
 * passphrase (PBKDF2-SHA256 600000 -> AES-GCM), same scheme as the
 * class-console and poll-admin payloads. Safe to publish.
 */
window.POLL_SECRET_PAYLOAD = {"salt": "Tu4XdZV5RbkVEEeLznVTWw==", "iv": "JTJNLMp3CGoEhntI", "ct": "GKwx4gAbNRJMeFmlALyDrmLJrat1LxMHnGdSLWRIc02er47Zc+AaonjkxftlRutuN/fv0vtX8TBYPA1Mud3HY3m7FABhbPMdvgAgIyym", "iter": 600000};
